name: spec
on: [pull_request]
jobs:
  minitest:
    name: minitest
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Sleep?
        run: sleep 5
      - name: Run tests
        run: |
          ruby -Ilib:test test/*
